ignore = [
    "src/../target/flatbuffers/mod.rs",
    "src/../target/flatbuffers/chess/game_generated.rs",
    "src/../target/flatbuffers/chess/game_list_generated.rs",
    "src/steps.rs",
    "tests/integration_tests.rs"
]