[package]
name = "chess_analytics"
version = "0.1.0"
authors = ["Sam Goldman <sgoldman216@gmail.com>"]
edition = "2018"

[lib]
name = "chess_analytics"
path = "src/lib.rs"

[[bin]]
name = "chess_analytics"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "2.0.0"
lazy_static = "1.4.0"
regex = "1.4.2"
glob = "0.3.0"
bzip2 = "0.4.1"
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.17"
#serde_json = "1.0"
#indicatif = { version = "*", features = ["rayon"] }
itertools = "0.10.0"
strum = "0.21.0"
strum_macros = "0.21"
mockall = "0.10.2"
no-panic = "0.1.15"
tui = { version = "0.16.0", features = ["rustbox"] }
termion = "1.5.6"
crossterm = "0.22"

[dev-dependencies]
assert_cmd = "0.10"
predicates = "1"

[build-dependencies]
flatc-rust = "0.2.0"
mktemp = "0.4.0"

[profile.dev]
opt-level = 3
