[package]
name = "chess_analytics"
version = "0.1.0"
authors = ["Sam Goldman <sgoldman216@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "chess_analytics"
path = "src/lib.rs"
test = true

[dependencies]
flatbuffers = "2.0.0"
lazy_static = "1.4.0"
regex = "1.4.2"
clap = "3.0.0-beta.2"
glob = "0.3.0"
bzip2 = "0.4.1"
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.15"
serde_json = "1.0"
indicatif = {version = "*", features = ["rayon"]}
itertools = "0.10.0"
log = "0.4.14"
simple_logger = "1.11.0"

[build-dependencies]
flatc-rust = "0.2.0"
mktemp = "0.4.0"

[profile.dev]
opt-level = 3
