[package]
name = "chess_analytics"
version = "0.1.0"
authors = ["Sam Goldman <sgoldman216@gmail.com>"]
edition = "2021"

[lib]
name = "chess_analytics"
path = "src/lib.rs"

[[bin]]
name = "chess_analytics"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "2.0.0"
lazy_static = "1.4.0"
regex = "1.6.0"
glob = "0.3.0"
bzip2 = "0.4.1"
rayon = "1.5.3"
serde = { version = "1.0.139", features = ["derive"] }
serde_yaml = "0.8.24"
itertools = "0.10.0"
mockall = "0.11.1"
mockall_double = "0.3.0"
tui = "0.18.0"
termion = "1.5.6"
crossterm = "0.24.0"

[dev-dependencies]
predicates = "2.1.1"

[build-dependencies]
flatc-rust = "0.2.0"
mktemp = "0.4.0"

[profile.dev]
opt-level = 3
