[package]
name = "chess_analytics"
version = "0.1.0"
authors = ["Sam Goldman <sgoldman216@gmail.com>"]
edition = "2021"

[lib]
name = "chess_analytics"
path = "src/lib.rs"

[[bin]]
name = "chess_analytics"
path = "src/main.rs"

[dependencies]
flatbuffers = "2.1.2"
regex = "1.6.0"
glob = "0.3.0"
bzip2 = "0.4.3"
rayon = "1.5.3"
serde = { version = "1.0.143", features = ["derive"] }
serde_yaml = "0.9.9"
itertools = "0.10.3"
mockall = "0.11.2"
mockall_double = "0.3.0"
tui = "0.18.0"
termion = "1.5.6"
postcard = { version = "1.0.1", features = ["alloc"] }
packed_struct = "0.10.0"
crossterm = "0.25.0"
# mutagen = { path = "../mutagen/mutagen", optional = true }
mutagen = { git = "https://github.com/llogiq/mutagen", optional = true }

[dev-dependencies]
predicates = "2.1.1"

[build-dependencies]
flatc-rust = "0.2.0"
mktemp = "0.4.1"

[profile.dev]
opt-level = 3

[features]
with_mutagen = ["mutagen"]