on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - run: chmod u+x ./scripts/install-flatbuffers.sh
      - uses: seanmiddleditch/gha-setup-ninja@master
      - run: ./scripts/install-flatbuffers.sh
      - uses: actions-rs/cargo@v1
        with:
          command: check
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: check-archive
          path: ./
      - uses: Swatinem/rust-cache@v1

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - run: chmod u+x ./scripts/install-flatbuffers.sh
      - uses: seanmiddleditch/gha-setup-ninja@master
      - run: ./scripts/install-flatbuffers.sh
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: Swatinem/rust-cache@v1

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - run: chmod u+x ./scripts/install-flatbuffers.sh
      - uses: seanmiddleditch/gha-setup-ninja@master
      - run: ./scripts/install-flatbuffers.sh
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          timeout: '3600'
          args: '--ignore-tests'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
      - uses: Swatinem/rust-cache@v1
          
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          override: true
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - run: chmod u+x ./scripts/install-flatbuffers.sh
      - uses: seanmiddleditch/gha-setup-ninja@master
      - run: ./scripts/install-flatbuffers.sh
      - uses: actions-rs/cargo@v1
        with: 
          command: build
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - uses: Swatinem/rust-cache@v1

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - run: chmod u+x ./scripts/install-flatbuffers.sh
      - uses: seanmiddleditch/gha-setup-ninja@master
      - run: ./scripts/install-flatbuffers.sh
      - uses: actions-rs/cargo@v1
        with: 
          command: build
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
