on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - run: chmod u+x ./scripts/install-flatbuffers.sh
      - uses: seanmiddleditch/gha-setup-ninja@master
      - run: ./scripts/install-flatbuffers.sh
      - uses: actions-rs/cargo@v1
        with:
          command: check
      # - uses: Swatinem/rust-cache@v1

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - run: chmod u+x ./scripts/install-flatbuffers.sh
      - uses: seanmiddleditch/gha-setup-ninja@master
      - run: ./scripts/install-flatbuffers.sh
      - uses: actions-rs/cargo@v1
        with:
          command: test
      # - run: cargo install cargo-tarpaulin
      # - run: cargo tarpaulin --out Xml
      # - run: bash <(curl -s https://codecov.io/bash)
      # - uses: Swatinem/rust-cache@v1
          
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - run: chmod u+x ./scripts/install-flatbuffers.sh
      - uses: seanmiddleditch/gha-setup-ninja@master
      - run: ./scripts/install-flatbuffers.sh
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with: 
          command: build
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      # - uses: Swatinem/rust-cache@v1

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - run: chmod u+x ./scripts/install-flatbuffers.sh
      - uses: seanmiddleditch/gha-setup-ninja@master
      - run: ./scripts/install-flatbuffers.sh
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with: 
          command: build
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
