on: [push]

name: Rust Package Preview

jobs:
  find_outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - run: chmod u+x ./scripts/install-flatbuffers.sh
      - uses: seanmiddleditch/gha-setup-ninja@master
      - run: ./scripts/install-flatbuffers.sh
      - run: cargo install --locked cargo-outdated
      - run: cargo outdated -R --format json | tee outdated.json
      - run: python scripts/outdated_to_matrix.py
      - uses: Swatinem/rust-cache@v1
    outputs:
      matrix: ${{ steps.find_outdated.outputs.matrix }}
  test_outdates:
    needs: find_outdated
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.find_outdated.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.package }}
      - run: echo ${{ matrix.package.name }}
      - run: echo ${{ matrix.package.latest }}